---
title: "Population genomics in practice"
subtitle: "Welcome and information"
author:
    - "Per Unneberg"
date: "`r format(Sys.time(), '%d %B, %Y')`"
institute: NBIS
from: markdown+emoji
format:
  revealjs:
    theme:
      - white
      - ../nbis.scss
    self-contained: true
    toc: false
    toc-depth: 1
    slide-level: 3
    slide-number: true
    preview-links: true
    chalkboard: false
    footer: Welcome
    logo: https://nbis.se/assets/img/logos/nbislogo-green.svg
    smaller: true
    highlight-style: gruvbox
    fig-height: 12
    fig-width: 10
    navigation-mode: vertical
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
execute:
  echo: true
  warning: false
  cache: true
  include: true
  autodep: true
  eval: true
  error: true
opts:
  knitr:
    code-fold: true
    tidy: true
    fig-format: svg
---

### Setup  {visibility="hidden" .unnumbered .unlisted}

```{r libs}
#| echo: false
#| eval: true
#| cache: false
library(knitr)
library(ggplot2)
library(viridis)
library(dotenv)
bw <- theme_bw(base_size=18) %+replace% theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
theme_set(bw)
knitr::knit_hooks$set(inline = function(x) {
                      prettyNum(x, big.mark=" ")
                  })
```
```{r }
#| label: utility-functions
#| echo: false
#| eval: true
#| cache: false
```


### Welcome to population genomics in practice

### Who are we?



### Who are you?

::: {.callout-warning}

:::

### Where are we?

Information about Navet: safety etc

### Code of conduct



# Schedule

```{r }
#| label: load-schedule
#| echo: false
#| eval: true
library(knitr)
schedule <- read.table("../schedule.tsv", sep="\t", header=TRUE, fill=TRUE)
colnames(schedule)[5] <- "Lecturer / TA"
days <- c("Monday", "Monday (alt)", "Tuesday", "Wednesday", "Thursday", "Friday")
i <- unlist(lapply(days, function(x) {grep(x, schedule$Day)}))
j <- c(i[2:length(i)], nrow(schedule) + 1) - i
schedule$split <- factor(rep(days, j), levels=days)
splitschedule <- split(schedule, schedule$split)
outcols <- c("Time", "Topic", "Lecturer / TA", "Type")
```

### Schedule - overview


### Monday 8 May

```{r }
#| label: schedule-monday
#| echo: false
#| eval: true
kable(splitschedule$Monday[, outcols], row.names=FALSE)
```


### Monday 8 May (alt)

```{r }
#| label: schedule-monday-alt
#| echo: false
#| eval: true

kable(splitschedule[["Monday (alt)"]][, outcols], row.names=FALSE)
```



### Tuesday 9 May

```{r }
#| label: schedule-tuesday
#| echo: false
#| eval: true

kable(splitschedule$Tuesday[, outcols], row.names=FALSE)
```


### Wednesday 10 May

```{r }
#| label: schedule-wednesday
#| echo: false
#| eval: true

kable(splitschedule$Wednesday[, outcols], row.names=FALSE)
```


### Thursday 11 May

```{r }
#| label: schedule-thursday
#| echo: false
#| eval: true

kable(splitschedule$Thursday[, outcols], row.names=FALSE)
```

### Friday 12 May

```{r }
#| label: schedule-friday
#| echo: false
#| eval: true

kable(splitschedule$Friday[, outcols], row.names=FALSE)
```

# Exercises

### Monday 8 May





### Refs {.unnumbered .unlisted}

::: { #refs }
:::
