---
title: Population structure
author:
  - Nikolay Oskolkov
format: html
---

::: {.callout-important collapse=true}

#### {{< fa server >}} Compute environment setup

If you haven't already done so, please read [Compute
environment](../compute_environment/index.qmd) for information on how
to prepare your working directory.

:::

::: {.callout-tip collapse=true}

## Learning objectives

:::

::: {.callout-note collapse=true}

## Data setup

:::{.panel-tabset}

#### UPPMAX

#### Local

:::

:::

::: {.callout-note collapse=true}

## Tools

:::{.panel-tabset}

#### Listing

#### UPPMAX modules

Execute the following command to load modules:

```bash
module load uppmax bioinfo-tools ANGSD R_packages
```

#### Conda

Copy the contents to a file `environment.yml` and install packages
with `mamba env update -f environment.yml`.

```{lang="text" }
channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - r-base
  - angsd
```

:::

:::

## Jupyter notebooks

<!-- markdownlint-disable MD013 -->

The rendered notebook instructions are located as html files, with
embedded buttons to download the actual notebooks (keep an eye out for
the `Download Notebook` button in the top right), here:

<a class="quarto-notebook-link" id="nblink-1" href="pca_mds_toy_example.ipynb.html">Source:
pca_mds_toy_example.ipynb</a>

<a class="quarto-notebook-link" id="nblink-1" href="pca_admixture_1000G.html">Source: pca_admixture_1000G.ipynb</a>

<!-- markdownlint-enable MD013 -->

Notebooks are also available for download at <https://uppsala.instructure.com/courses/86976/pages/population-structure-notebooks>
