---
title: "Exercises"
subtitle: " 2023 PGIP • Population Genomics in Practice"
description: "List of all exercises"
listing:
  id: exercise-listings
  type: grid
  grid-columns: 4
  fields: [title, subtitle, author]
  sort: false
  contents:
    - compute_environment/index.qmd
    - datasets/monkeyflowers.qmd
    - simulation/index.qmd
    - variant_calling/index.qmd
    - variant_filtering/index.qmd
date: ""
toc: false
sidebar: false
format:
  html:
    number-sections: false
    page-layout: full
execute:
  freeze: false
---

## On self-assessment exercise blocks

Scattered throughout the documents are exercise blocks, with hidden
answers, and in some cases, hints. The exercises are for
self-assessment of your understanding, but they are not mandatory.

Some of the exercises (labelled with the linux penguin {{< fa
brands linux >}}) are related to the usage of the command line
interfaces (CLI), and how to obtain information about what a program
does. This is an essential skill when working in Linux/UNIX
environments! These exercises can be skipped if you are an experienced
Linux/UNIX user.

An example exercise is provided here:

::: {.callout-exercise}

## Example exercise block

{{< fa brands linux >}} The `ls` command is used to list the contents
of a directory. What option provides a so-called long listing format?

::: {.callout-hint}

Type `ls --help` to show the options to `ls`.

:::

::: {.callout-answer}

The `-l` option uses the long listing format, i.e., the command to use
is `ls -l`.

:::

:::

## Exercises
