---
title: "Schedule"
toc: false
sidebar: false
format:
  html:
    number-sections: false
---

<br>

[**This site is under construction!**]{.largest}

<br>

<br>

[**{{< meta date >}}: Note that the schedule is tentative and subject to change!**]{.largest}

<br>

<!-- markdownlint-disable MD013 -->

::: {.contents-table .column-body-outset}

| Topic                                      | Time        | Author         | Links                                                                                                                         |
|--------------------------------------------|-------------|----------------|-------------------------------------------------------------------------------------------------------------------------------|
| [6-Nov-2023 (Mon)]{.highlight}             |             |                |                                                                                                                               |
| Coffee and welcome                         | 08:30-09:00 |                |                                                                                                                               |
| Introduction to PGIP                       | 09:00-09:30 | AS, JH, NO, PU |                                                                                                                               |
| Population genomics in practice            | 09:30-10:00 | PU             | [Slides](slides/pgip/index.html)                                                                                              |
| Coffee break                               | 10:00-10:30 |                |                                                                                                                               |
| Population genetics foundations            | 10:30-12:00 | PU             | [Slides](slides/foundations/index.html)                                                                                       |
| Lunch                                      | 12:00-13:00 |                |                                                                                                                               |
| Introduction to the coalescent             | 13:00-15:00 | PU             | [Slides](slides/simulation/index.html), [Instructions]({{< var lab.sim.howto >}}), [Exercise]({{< var lab.sim.coalescent >}}) |
| Coffee break                               | 15:00-15:30 |                |                                                                                                                               |
| Introduction to msprime                    | 15:30-17:00 | PU             | [Slides](slides/simulation/index.html), [Exercise]({{< var lab.sim.msprime >}})                                               |
|                                            |             |                |                                                                                                                               |
| [7-Nov-2023 (Tue)]{.highlight}             |             |                |                                                                                                                               |
| Recap day 1                                | 09:00-09:30 | PU             |                                                                                                                               |
| Variant calling and filtering              | 09:30-10:00 | PU             | Slides, Exercise                                                                                                              |
| Coffee break                               | 10:00-10:30 |                |                                                                                                                               |
| Variant calling and filtering, continued   | 10:30-12:00 | PU             | Slides, Exercise                                                                                                              |
| Lunch                                      | 12:00-13:00 |                |                                                                                                                               |
| Genetic diversity                          | 13:00-15:00 | PU             | Slides, Exercise                                                                                                              |
| Coffee break                               | 15:00-15:30 |                |                                                                                                                               |
| Genetic diversity, continued               | 15:30-17:00 | PU             |                                                                                                                               |
|                                            |             |                |                                                                                                                               |
| [8-Nov-2023 (Wed)]{.highlight}             |             |                |                                                                                                                               |
| Recap day 2                                | 09:00-09:30 | PU             |                                                                                                                               |
| Population structure                       | 09:30-10:00 | NO             | [Slides](slides/population_structure/index.html)                                                                              |
| Coffee break                               | 10:00-10:30 |                |                                                                                                                               |
| Population structure, continued            | 10:30-12:00 | NO             |                                                                                                                               |
| Lunch                                      | 12:00-13:00 |                |                                                                                                                               |
| Population structure, continued            | 13:00-15:00 | NO             |                                                                                                                               |
| Coffee break                               | 15:00-15:30 |                |                                                                                                                               |
| Population structure, continued            | 15:30-17:00 | NO             |                                                                                                                               |
|                                            |             |                |                                                                                                                               |
| [9-Nov-2023 (Thu)]{.highlight}             |             |                |                                                                                                                               |
| Recap day 3                                | 09:00-09:30 | NO             |                                                                                                                               |
| Demography                                 | 09:30-10:00 | AS             |                                                                                                                               |
| Coffee break                               | 10:00-10:30 |                |                                                                                                                               |
| Demography and psmc                        | 10:30-12:00 | AS             |                                                                                                                               |
| Lunch                                      | 12:00-13:00 |                |                                                                                                                               |
| Selection                                  | 13:00-15:00 | JH             |                                                                                                                               |
| Coffee break                               | 15:00-15:30 |                |                                                                                                                               |
| Selection                                  | 15:30-17:00 | JH             |                                                                                                                               |
|                                            |             |                |                                                                                                                               |
| [10-Nov-2023 (Fri)]{.highlight}            |             |                |                                                                                                                               |
| Recap                                      | 09:00-10:00 | JH, NO, PU, AS |                                                                                                                               |
| Coffee break                               | 10:00-10:30 |                |                                                                                                                               |
| Guest lecture                              | 10:30-11:30 |                |                                                                                                                               |
| Recap continued                            | 11:30-12:00 | JH, NO, PU, AS |                                                                                                                               |
| Lunch                                      | 12:00-13:00 |                |                                                                                                                               |
| Project discussion / networking / own time | 13:00-17:00 |                |                                                                                                                               |

:::

<!-- markdownlint-enable -->
