---
title: "Population admixture"
subtitle: "Admixture"
author:
    - "Per Unneberg"
format:
  revealjs:
    footer: Population admixture
---

## Setup  {visibility="hidden" .unnumbered .unlisted}

{{< include ../_knitr.qmd >}}

{{< include ../_rlibs.qmd >}}

::: {.notes }

Outline:

- what is admixture?
- why do we do it?
  - population history
  - correction for GWAS
  - breeding: failure to account for admixture leads to overestimate
    of hereditability
  - identify pure subpopulations for, e.g., prediction via pca
- methods and theory
  - f-statistics
  - TreeMix
  - qpGraph
  - ADMIXTURE - estimates *proportions* of admixture and does not say
    whether admixture has ocurred or not; cf population structure

Exercise:

- admixtools2?

:::

# Admixture and f-statistics

Focus more generally on admixture and f-statistics

## Admixture

- *f4*-statistics

Base on [@peter_AdmixturePopulationStructure_2016] and
[@lipson_ApplyingF4statisticsAdmixture_2020]

## Admixture models

See [@maier_LimitsFittingComplex_2022], [@maierrobert_PaperNotes_2022]

## Refs {.unnumbered .unlisted}

::: { #refs }
:::
