---
title: "Population structure"
subtitle: "Fixation indices, admixture and more"
author:
    - "Per Unneberg"
format:
  revealjs:
    footer: Population structure
---

## Setup  {visibility="hidden" .unnumbered .unlisted}

{{< include ../_knitr.qmd >}}

{{< include ../_rlibs.qmd >}}

# Population structure

::: {.notes }

On the limited applicability of the expected value of F_ST, [p. 243
@nei_MolecularEvolutionPhylogenetics_2000]:

- assumes idealized population structure, all subpopulations derived
  at same time (equal size, no demographic history)
- in practice difficult to know demographic history
- most natural populations do have unique phylogenetic structure

More general exposition of f_st, Wahlund effect, etc

:::

## The independent population model

```{r, engine='tikz', fig.ext="svg"}
#| label: fst-independent-population-model
#| echo: false
#| eval: true
#| out-height: 300px
#| fig-height: 300px
\tikzset{pop/.style={circle, text width=20, align=center, draw, minimum width=10}}
\begin{tikzpicture}[x=1pt, y=1pt, node distance=150]
\node[pop] (pop0) at (0,0) {Pop. 0};
\node[pop, below of=pop0] (popC) {Pop. C};
\node[pop, left of=popC] (popB) {Pop. B};
\node[pop, left of=popB] (popA) {Pop. A};
\node[right of=popC, node distance=75] (dot1) {...};
\node[right of=dot1, node distance=75] (dot2) {...};
\node[right of=dot2, node distance=75] (dot3) {...};
\node[pop, right of=dot3, node distance=75] (popK) {Pop. K};
\draw (pop0) edge node[above] {$\theta_A$} (popA);
\draw (pop0) edge node[left] {$\theta_B$} (popB);
\draw (pop0) edge node[left] {$\theta_C$} (popC);
\draw (pop0) edge node[above] {$\theta_K$} (popK);
\draw (current bounding box.north east)
  -- (current bounding box.north west)
  -- (current bounding box.south west)
  -- (current bounding box.south east)
  -- cycle;
\end{tikzpicture}
```

[@mary-huard_FastAccurateJoint_2023]

## $F_{ST}$ estimators

Table S2 in [@bhatia_EstimatingInterpretingFST_2013]

<!-- markdownlint-disable MD013 -->

| **Conceptual definition**                        | **Citation** | **Evolutionary assumptions**                               | **WC**                                                         | **Nei** | **Hudson** |
|--------------------------------------------------|--------------|------------------------------------------------------------|----------------------------------------------------------------|---------|------------|
| Ratio of variances / Correlation between alleles |              | SNPs analyzed were polymorphic in the ancestral population | $F_{ST}$ is identical across populations OR Equal sample sizes | No^c    | Yes^*      |
|                                                  |              |                                                            |                                                                |         |            |

<!-- markdownlint-disable MD013 -->

### Weir Cockerham

- correlation randomly uniting gametes / ratio of variance between
  populationss to total variance
- "total population" is most recent common ancestral population
  (figure previous slide)
- sites are polymorphic in ancestral
- $F_{ST}$ identical for each population

=> populations are replicates of identical evolutionary history =>

Interprentation: F_{ST} is a parameter

#### Nei

Interpretation: F_{ST} is a statistic

#### Hudson

::: {.notes }

[@excoffier_AnalysisPopulationSubdivision_2004] provides pros/cons for
WC vs Nei.

[@mary-huard_FastAccurateJoint_2023] shows that Weir vs Hudson compare
different branch lengths

[@bhatia_EstimatingInterpretingFST_2013] multiple estimators make
correct choice of estimator unclear.

Different estimators due to confusion as to what Wright meant by
"total population": for Nei is the combination of two populations. For
WC it is the most recent ancestral population. Hence, Nei's F_ST is a
statistic, whereas for WC it is a parameter of an evolutionary process

:::

## On the impact of rare variants

FIXME: include stat/figure on how different estimators give different
results

::: {.notes }

Different estimators can give different results; e.g., 2-fold
difference for human samples in
[@bhatia_EstimatingInterpretingFST_2013]. This difference, they show,
is mainly due to ascertainment and using average of ratios (instead of
ratio of averages) when combining estimates

:::

## Recommendations

::: {.notes }

[@bhatia_EstimatingInterpretingFST_2013] recommend Hudson. They observe

:::

## Refs {.unnumbered .unlisted}

::: { #refs }
:::
